name: Android CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest  # Use macOS machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust the Java version as needed

      - name: Set up Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29  # Adjust the API level as needed
          ndk: 21.0.6113669  # Adjust NDK version if needed
          cmake: 3.10.2.4988404  # Adjust CMake version if needed
          distribution: 'google_apis'  # Specify the emulator image distribution
          script: ./gradlew connectedCheck

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build and Test
        run: ./gradlew build
        env:
          JVM_OPTS: -Xmx512m  # Adjust memory settings as needed
          GRADLE_OPTS: -Dorg.gradle.daemon=false  # Disable Gradle daemon for CI

  release:
    name: Build and Release
    runs-on: macos-latest  # Use macOS machine
    needs: build
    if: github.ref == 'refs/heads/main'  # Release only from the main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust the Java version as needed

      - name: Set up Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29  # Adjust the API level as needed
          ndk: 21.0.6113669  # Adjust NDK version if needed
          cmake: 3.10.2.4988404  # Adjust CMake version if needed
          distribution: 'google_apis'  # Specify the emulator image distribution
          script: ./gradlew connectedCheck

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew bundleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: app/build/outputs/bundle/release/app-release.aab