name: Android CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest  # Use macOS machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust the Java version as needed

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.28.0
        with:
          api-level: 29  # Adjust the API level as needed
          emulator-image: system-images;android-29;google_apis;x86_64  # Adjust the emulator image as needed
          script: ./gradlew connectedCheck

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build and Test
        run: ./gradlew build
        env:
          JVM_OPTS: -Xmx512m  # Adjust memory settings as needed
          GRADLE_OPTS: -Dorg.gradle.daemon=false  # Disable Gradle daemon for CI

  release:
    name: Build and Release
    runs-on: macos-latest  # Use macOS machine
    needs: build
    if: github.ref == 'refs/heads/main'  # Release only from the main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust the Java version as needed

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.28.0
        with:
          api-level: 29  # Adjust the API level as needed
          emulator-image: system-images;android-29;google_apis;x86_64  # Adjust the emulator image as needed
          script: ./gradlew connectedCheck

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew bundleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: app/build/outputs/bundle/release/app-release.aab